name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
send_metrics = false

[vars]
GITHUB_CLIENT_ID = "${env:GITHUB_CLIENT_ID}"
GITHUB_CLIENT_SECRET = "${env:GITHUB_CLIENT_SECRET}"
GITHUB_CALLBACK_URL = "${env:GITHUB_CALLBACK_URL}"
GOOGLE_CLIENT_ID = "${env:GOOGLE_CLIENT_ID}"
GOOGLE_CLIENT_SECRET = "${env:GOOGLE_CLIENT_SECRET}"
GOOGLE_CALLBACK_URL = "${env:GOOGLE_CALLBACK_URL}"
SESSION_SECRET = "${env:SESSION_SECRET}"
STRIPE_SECRET_KEY = "${env:STRIPE_SECRET_KEY}"
STRIPE_SUCCESS_URL = "${env:STRIPE_SUCCESS_URL}"
STRIPE_CANCEL_URL = "${env:STRIPE_CANCEL_URL}"
STRIPE_WEBHOOK_SECRET = "${env:STRIPE_WEBHOOK_SECRET}"
VITE_API_URL = "${env:VITE_API_URL}"