name ="bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-02"
pages_build_output_dir ="./build/client"
send_metrics = false

[vars]
GITHUB_CLIENT_ID = "Iv23lihykFEzfYwD1ATZ"
GITHUB_CLIENT_SECRET = "7fa56ccce1b8f55403dc1b84ba45732f42982f42"
GITHUB_CALLBACK_URL = "http://localhost:5173/auth/github/callback"

GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_CALLBACK_URL = "http://localhost:5173/auth/google/callback"
DIRECT_URL = "postgresql://postgres.vsbykplluceswfuyjtzc:qrS3PxBolNDBdaFu@aws-0-us-west-1.pooler.supabase.com:5432/postgres?pgbouncer=true"
SESSION_SECRET = "ca191dbccd08a854edb7d2842a083c75277cfdc0494548a3c61aee81e56df76d"

DATABASE_URL = "postgresql://postgres.vsbykplluceswfuyjtzc:qrS3PxBolNDBdaFu@aws-0-us-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

STRIPE_SECRET_KEY = "sk_test_51LmvlhLwHVywsqUKn6A3qnjp2tLfapAZgRIHForKe9TtjkFeHT1cTUTBPtVGmpS8U4VKQkIQwrDYyMD3Flr5Gg2200NeiyZGgz"
STRIPE_SUCCESS_URL = "http://localhost:5173/"
STRIPE_CANCEL_URL = "http://localhost:5173/"
STRIPE_WEBHOOK_SECRET = "whsec_aea2922310385ce694a23532c328d00d5322ed93654a4a27220877d7472c8f5f"